# General Settings
set -g default-terminal "screen-256color"
set -g default-shell /bin/zsh
set -g history-limit 50000
set -g escape-time 10
set -g detach-on-destroy off
set -g focus-events on
set -g allow-passthrough on
set -g xterm-keys on
set -g mode-keys vi
set -g mouse on

# Status Line Configuration
set -g status-position bottom
set -g status-left-length 10
set -g status-interval 60

# Window and Pane Behavior
set -g base-index 1
set -g pane-base-index 1
set -g pane-border-style "fg=magenta"
set -g pane-active-border-style "fg=green,bg=default"
set -g display-panes-time 100000
set -g pane-border-status top
set -g pane-border-format " #P: #{pane_current_command} in #{pane_current_path} "

# Status Line Formats
set -g window-status-format "#[fg=#44475a]#{?pane_synchronized,💢 ,} #I #{pane_current_command} #{?window_zoomed_flag,👀 ,}#[default]"
set -g window-status-current-format "#[fg=black,bg=#bd93f9,nobold] ❯ #[bold]#I #[fg=black]#{pane_current_command} #[fg=black]#{?window_zoomed_flag,🔍,}#{?pane_synchronized,💢,}#[default]"
set -g window-active-style 'bg=#000000'
set -g window-style 'bg=#0B0B0B'
set -g status-right "#[fg=#fff] Tartarus #[fg=#fff]| %H:%M #[fg=#fff]%d-%b-%y"

# Key Bindings
unbind C-b
set -g prefix C-Space
bind r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# Plugin manager (if you want to use it)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
